SNOWFLAKE_USER = "AUTOMATION"
SNOWFLAKE_PASSWORD = "1990Snowflake!"
SNOWFLAKE_ACCOUNT = "SLPNPZF-UAB68321"  # e.g. xy12345.us-east-1
SNOWFLAKE_WAREHOUSE = "COMPUTE_WH"
SNOWFLAKE_DATABASE = "INVOICE_DB"
SNOWFLAKE_SCHEMA = "PUBLIC"
# Optional:
# SNOWFLAKE_ROLE = "ACCOUNTADMIN"
